### ISSUE TITLE
New tools site has removed old static images so emails have no logo

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster-notify#15]
After thinking about this for a bit, I think the best option is to host our static assets somewhere... static. If it is just this logo we care about, we can serve it from notify directly, but if we want to have a general place for things to go grab tc images and other assets, perhaps a dedicated directory of the tools site would make sense? I think as a short-term fix I might make this point at the docs site, but that will change eventually as well so we should fix this more permanently.

@djmitche @eliperelman any thoughts?

**Comment by djmitche** [comment]
https://taskcluster-static.websites-us-east-1.s3.amazonws.com?

**Comment by imbstack** [comment]
That makes sense to me. I'm envisioning a repo that just has static assets in it and tc can push it up there when we push. No need for a cdn for now. If that makes sense to you, I can make that happen.

**Comment by jonasfj** [comment]
Isn't it simpler to serve this from tc-notify, that way you don't have to create an S3 bucket to deploy tc-notify... It's not like we're serving this very often..

**Comment by imbstack** [comment]
Ok, I've made it use a docs site thing for now. We can delay figuring out a long-term solution for a bit.

**Comment by imbstack** [comment]
I think the only question is: "how many static assets do we have and how many times will they need to be accessed outside of docs/tools".

Ok, that's two questions, but still :p

**Comment by eliperelman** [comment]
The issue with serving them from "tools" is that, by default, the image will be versioned, which is OK until a modification is made to the image, and then it will get a new URL. This of course can be overridden, but just a thought.

I wouldn't mind a bucket/CDN for some things like logos, etc.
