### ISSUE TITLE
Allow setting your own message for email/irc messages.

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster-notify#16]
Currently irc messages have [a preset message](https://github.com/taskcluster/taskcluster-notify/blob/master/src/handler.js#L63). It would be nice if users could set their own message (we've had a few people ask about it in the channel recently). I propose we allow this via adding a `task.extra.notify` field and allowing users to set the message for their task there with a key like `ircMessage`. For whoever implements this, note that we already have loaded the task definition in by the time you will need it [here](https://github.com/taskcluster/taskcluster-notify/blob/master/src/handler.js#L41). Just check to see if it has `extra.notify.<whatever we call this>` and you are good to go.

One thing to discuss is whether or not we want to allow people to make the string be a template. I could see this being useful to set things like links or status or whatever. We could possibly make the entire contents of the [status](https://github.com/taskcluster/taskcluster-notify/blob/master/src/handler.js#L42) results available to be interpolated in?

**Comment by djmitche** [comment]
Maybe JSON-e?

**Comment by rail** [comment]
I'd also add email to the scope.

**Comment by imbstack** [comment]
This should be added in #17. I'll test it out for a bit and close this if it seems to work!

**Comment by imbstack** [comment]
Seemed to work [here](https://tools.taskcluster.net/groups/KtXxCCCQQYiUgEDPbqDi1A/tasks/KtXxCCCQQYiUgEDPbqDi1A/details).

Sidenote: what a great taskId that task had. Lots of double/triple characters.

**Comment by imbstack** [comment]
Docs are https://docs.taskcluster.net/reference/core/taskcluster-notify/docs/usage#setting-custom-messages
