### ISSUE TITLE
Option to supress notifications for cancelled tasks

### ISSUE THREAD

**Issue by nthomas-mozilla** [taskcluster/taskcluster-notify#23]
Firefox releases running on TC have fairly big graphs, ~4500 jobs, and we switched to using taskcluster-notify in [bug 1425571](https://bugzilla.mozilla.org/show_bug.cgi?id=1425571). 

Sometimes we need to cancel the whole graph, and all the tasks end up with `state: exception` and `reason: cancelled`. We set a `notify.email.[email].on-exception` route to catch tasks that fail due to infra or other faults and will require our attention to keep the release rolling. As a result we get a lot of email when cancelling a whole graph.

Is there some way we could augment tc-notify to suppress notifications when whole graphs are cancelled ? Some quick ideas:
* a new option `task.extra.notify.suppressCancellations`
* new route `notify.email.<you@you.com>.on-exception-less-cancel`  (ugh!)

A possible workaround could be to use `${status.runs[-1].reasonResolved}` in the subject and filter away cancelled, but would be great to avoid mail in the first place.

**Comment by nthomas-mozilla** [comment]
@imbstack, any thoughts/preferences on how we could proceed here ?

**Comment by imbstack** [comment]
Ah, sorry I missed this when it was created.

Could we also do something like setting an upper limit for emails per task-graph per hour? I think we could implement that in taskcluster-notify without too much effort. 

Other than that idea, `task.extra.notify.suppressCancellations` is a bit of a mouthful but I think it would work fine or we can come up with something nicer than `on-exception-less-cancel`. I wish we could change the meaning of `on-exception` now, but I guess the cat is out of the bag.

**Comment by imbstack** [comment]
@nthomas-mozilla just pinging you here since I didn't last when I wrote this.

**Comment by jonasfj** [comment]
I would propose to just always ignore cancellations, since they are usually deliberate actions anyways.

I filed https://github.com/taskcluster/taskcluster-notify/pull/29 before I saw this issue.

**Comment by nthomas-mozilla** [comment]
With #31 ignoring cancelled and deadline-exceeded, and RelEng drastically reducing our use of tc-notify, this turns into a WONTFIX.
